/**
 * Paises do cadastro, com o nome e a ordem ja resolvidos por idioma.
 *
 * O cadastro guarda o codigo ISO de dois digitos, nao o nome escrito. Duas
 * razoes.
 *
 * 1. O nome depende do idioma de quem preenche. Sem codigo, a mesma pessoa
 *    entraria como "Brasil" em portugues, "Brazil" em ingles e "Brasil" em
 *    espanhol, e o painel da equipe leria tres paises onde ha um.
 * 2. O nome depende de quem digita. Em campo livre, "EUA", "Estados Unidos" e
 *    "United States" sao tres linhas diferentes de uma lista que deveria ter
 *    uma.
 *
 * POR QUE NOME E ORDEM ESTAO ESCRITOS AQUI, e nao saem de Intl em tempo de
 * execucao: o site e pre-renderizado em Node e hidratado no navegador, e as
 * duas implementacoes de ICU nao concordam nem no nome que devolvem nem na
 * ordem alfabetica que produzem. Isso dava erro de hidratacao em TODA pagina
 * que monta este seletor. Com a lista escrita e ja ordenada, servidor e
 * navegador geram exatamente o mesmo HTML, e nenhuma comparacao de texto
 * acontece em tempo de execucao.
 *
 * PARA ACRESCENTAR UM PAIS: ponha o codigo no lugar certo das tres listas de
 * ordem e o nome nos tres mapas. Para nao traduzir a mao:
 *   new Intl.DisplayNames(['pt-BR'], { type: 'region' }).of('NG')
 *   new Intl.DisplayNames(['en'], { type: 'region' }).of('NG')
 *   new Intl.DisplayNames(['es'], { type: 'region' }).of('NG')
 */

import type { Idioma } from '@/i18n/idiomas';

/** O codigo do pais que o formulario ja vem marcando. */
export const PAIS_PADRAO = 'BR';

/** Codigos na ordem alfabetica do portugues. */
const ORDEM_PT: readonly string[] = [
  'ZA',
  'DE',
  'AO',
  'AR',
  'AU',
  'AT',
  'BE',
  'BZ',
  'BO',
  'BR',
  'CV',
  'CA',
  'CL',
  'CN',
  'CO',
  'KR',
  'CR',
  'CU',
  'DK',
  'SV',
  'AE',
  'EC',
  'ES',
  'US',
  'PH',
  'FI',
  'FR',
  'GR',
  'GT',
  'GY',
  'GQ',
  'GW',
  'HT',
  'HN',
  'HU',
  'IN',
  'ID',
  'IE',
  'IS',
  'IT',
  'JM',
  'JP',
  'LU',
  'MO',
  'MA',
  'MX',
  'MZ',
  'NI',
  'NG',
  'NO',
  'NZ',
  'NL',
  'PA',
  'PY',
  'PE',
  'PL',
  'PR',
  'PT',
  'KE',
  'GB',
  'DO',
  'RO',
  'ST',
  'SG',
  'SE',
  'CH',
  'SR',
  'CZ',
  'TL',
  'TT',
  'TR',
  'UY',
  'VE',
];

/** Codigos na ordem alfabetica do ingles. */
const ORDEM_EN: readonly string[] = [
  'AO',
  'AR',
  'AU',
  'AT',
  'BE',
  'BZ',
  'BO',
  'BR',
  'CA',
  'CV',
  'CL',
  'CN',
  'CO',
  'CR',
  'CU',
  'CZ',
  'DK',
  'DO',
  'EC',
  'SV',
  'GQ',
  'FI',
  'FR',
  'DE',
  'GR',
  'GT',
  'GW',
  'GY',
  'HT',
  'HN',
  'HU',
  'IS',
  'IN',
  'ID',
  'IE',
  'IT',
  'JM',
  'JP',
  'KE',
  'LU',
  'MO',
  'MX',
  'MA',
  'MZ',
  'NL',
  'NZ',
  'NI',
  'NG',
  'NO',
  'PA',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'PR',
  'RO',
  'ST',
  'SG',
  'ZA',
  'KR',
  'ES',
  'SR',
  'SE',
  'CH',
  'TL',
  'TT',
  'TR',
  'AE',
  'GB',
  'US',
  'UY',
  'VE',
];

/** Codigos na ordem alfabetica do espanhol. */
const ORDEM_ES: readonly string[] = [
  'DE',
  'AO',
  'AR',
  'AU',
  'AT',
  'BE',
  'BZ',
  'BO',
  'BR',
  'CV',
  'CA',
  'CZ',
  'CL',
  'CN',
  'CO',
  'KR',
  'CR',
  'CU',
  'DK',
  'EC',
  'SV',
  'AE',
  'ES',
  'US',
  'PH',
  'FI',
  'FR',
  'GR',
  'GT',
  'GQ',
  'GW',
  'GY',
  'HT',
  'HN',
  'HU',
  'IN',
  'ID',
  'IE',
  'IS',
  'IT',
  'JM',
  'JP',
  'KE',
  'LU',
  'MA',
  'MX',
  'MZ',
  'NI',
  'NG',
  'NO',
  'NZ',
  'NL',
  'PA',
  'PY',
  'PE',
  'PL',
  'PT',
  'PR',
  'MO',
  'GB',
  'DO',
  'RO',
  'ST',
  'SG',
  'ZA',
  'SE',
  'CH',
  'SR',
  'TL',
  'TT',
  'TR',
  'UY',
  'VE',
];

/** Nomes em portugues. */
const NOMES_PT: Record<string, string> = {
  ZA: "África do Sul",
  DE: "Alemanha",
  AO: "Angola",
  AR: "Argentina",
  AU: "Austrália",
  AT: "Áustria",
  BE: "Bélgica",
  BZ: "Belize",
  BO: "Bolívia",
  BR: "Brasil",
  CV: "Cabo Verde",
  CA: "Canadá",
  CL: "Chile",
  CN: "China",
  CO: "Colômbia",
  KR: "Coreia do Sul",
  CR: "Costa Rica",
  CU: "Cuba",
  DK: "Dinamarca",
  SV: "El Salvador",
  AE: "Emirados Árabes Unidos",
  EC: "Equador",
  ES: "Espanha",
  US: "Estados Unidos",
  PH: "Filipinas",
  FI: "Finlândia",
  FR: "França",
  GR: "Grécia",
  GT: "Guatemala",
  GY: "Guiana",
  GQ: "Guiné Equatorial",
  GW: "Guiné-Bissau",
  HT: "Haiti",
  HN: "Honduras",
  HU: "Hungria",
  IN: "Índia",
  ID: "Indonésia",
  IE: "Irlanda",
  IS: "Islândia",
  IT: "Itália",
  JM: "Jamaica",
  JP: "Japão",
  LU: "Luxemburgo",
  MO: "Macau, RAE da China",
  MA: "Marrocos",
  MX: "México",
  MZ: "Moçambique",
  NI: "Nicarágua",
  NG: "Nigéria",
  NO: "Noruega",
  NZ: "Nova Zelândia",
  NL: "Países Baixos",
  PA: "Panamá",
  PY: "Paraguai",
  PE: "Peru",
  PL: "Polônia",
  PR: "Porto Rico",
  PT: "Portugal",
  KE: "Quênia",
  GB: "Reino Unido",
  DO: "República Dominicana",
  RO: "Romênia",
  ST: "São Tomé e Príncipe",
  SG: "Singapura",
  SE: "Suécia",
  CH: "Suíça",
  SR: "Suriname",
  CZ: "Tchéquia",
  TL: "Timor-Leste",
  TT: "Trinidad e Tobago",
  TR: "Turquia",
  UY: "Uruguai",
  VE: "Venezuela",
};

/** Nomes em ingles. */
const NOMES_EN: Record<string, string> = {
  AO: "Angola",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  BE: "Belgium",
  BZ: "Belize",
  BO: "Bolivia",
  BR: "Brazil",
  CA: "Canada",
  CV: "Cape Verde",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CZ: "Czechia",
  DK: "Denmark",
  DO: "Dominican Republic",
  EC: "Ecuador",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  FI: "Finland",
  FR: "France",
  DE: "Germany",
  GR: "Greece",
  GT: "Guatemala",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IE: "Ireland",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  KE: "Kenya",
  LU: "Luxembourg",
  MO: "Macao SAR China",
  MX: "Mexico",
  MA: "Morocco",
  MZ: "Mozambique",
  NL: "Netherlands",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NG: "Nigeria",
  NO: "Norway",
  PA: "Panama",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  RO: "Romania",
  ST: "São Tomé & Príncipe",
  SG: "Singapore",
  ZA: "South Africa",
  KR: "South Korea",
  ES: "Spain",
  SR: "Suriname",
  SE: "Sweden",
  CH: "Switzerland",
  TL: "Timor-Leste",
  TT: "Trinidad & Tobago",
  TR: "Türkiye",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  VE: "Venezuela",
};

/** Nomes em espanhol. */
const NOMES_ES: Record<string, string> = {
  DE: "Alemania",
  AO: "Angola",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  BE: "Bélgica",
  BZ: "Belice",
  BO: "Bolivia",
  BR: "Brasil",
  CV: "Cabo Verde",
  CA: "Canadá",
  CZ: "Chequia",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  KR: "Corea del Sur",
  CR: "Costa Rica",
  CU: "Cuba",
  DK: "Dinamarca",
  EC: "Ecuador",
  SV: "El Salvador",
  AE: "Emiratos Árabes Unidos",
  ES: "España",
  US: "Estados Unidos",
  PH: "Filipinas",
  FI: "Finlandia",
  FR: "Francia",
  GR: "Grecia",
  GT: "Guatemala",
  GQ: "Guinea Ecuatorial",
  GW: "Guinea-Bisáu",
  GY: "Guyana",
  HT: "Haití",
  HN: "Honduras",
  HU: "Hungría",
  IN: "India",
  ID: "Indonesia",
  IE: "Irlanda",
  IS: "Islandia",
  IT: "Italia",
  JM: "Jamaica",
  JP: "Japón",
  KE: "Kenia",
  LU: "Luxemburgo",
  MA: "Marruecos",
  MX: "México",
  MZ: "Mozambique",
  NI: "Nicaragua",
  NG: "Nigeria",
  NO: "Noruega",
  NZ: "Nueva Zelanda",
  NL: "Países Bajos",
  PA: "Panamá",
  PY: "Paraguay",
  PE: "Perú",
  PL: "Polonia",
  PT: "Portugal",
  PR: "Puerto Rico",
  MO: "RAE de Macao (China)",
  GB: "Reino Unido",
  DO: "República Dominicana",
  RO: "Rumanía",
  ST: "Santo Tomé y Príncipe",
  SG: "Singapur",
  ZA: "Sudáfrica",
  SE: "Suecia",
  CH: "Suiza",
  SR: "Surinam",
  TL: "Timor-Leste",
  TT: "Trinidad y Tobago",
  TR: "Turquía",
  UY: "Uruguay",
  VE: "Venezuela",
};

const NOMES: Record<Idioma, Record<string, string>> = {
  pt: NOMES_PT,
  en: NOMES_EN,
  es: NOMES_ES,
};

const ORDEM: Record<Idioma, readonly string[]> = {
  pt: ORDEM_PT,
  en: ORDEM_EN,
  es: ORDEM_ES,
};

/**
 * Codigos aceitos, em ordem de codigo. Serve para validar, nao para exibir.
 *
 * Nao e a lista completa das Nacoes Unidas: e onde a INDICA tem ou pode ter
 * criador, que e America, Europa ocidental e as pracas de lingua portuguesa na
 * Africa e na Asia.
 */
export const PAISES: readonly string[] = [...ORDEM_PT].sort();

/** Nome do pais no idioma pedido. Codigo desconhecido aparece como ele mesmo. */
export function nomeDoPais(codigo: string, idioma: Idioma): string {
  return NOMES[idioma][codigo] ?? codigo;
}

/** A lista pronta para um seletor, na ordem alfabetica do idioma. */
export function opcoesDePais(idioma: Idioma): { valor: string; rotulo: string }[] {
  return ORDEM[idioma].map((codigo) => ({ valor: codigo, rotulo: NOMES[idioma][codigo] }));
}
